name: Build and release LaTeX documents
on: [push]
permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      
      - name: Setup TeXLive
        uses: teatimeguest/setup-texlive-action@v3
        with:
          cache: true
          packages: |
            scheme-basic
            latexmk
            llncs
            geometry
            silence
            fontenc
            lmodern
            babel
            csquotes
            microtype
            xpunctuate
            dirtytalk
            pifont
            tcolorbox
            pgf
            tikz
            xcolor
            amsmath
            amsthm
            mathtools
            todonotes
            biblatex
            biber
            hyperref
            cleveref
            cryptocode
            xpatch
            etoolbox
            xargs
            forloop
            array
            pbox
            varwidth
            bigfoot
            comment
            environ
            trimspaces
            fixcmex
            xkeyval
            bookmark
            graphics
            tools
            multirow
            listings
            varioref
            subfigure
            titlesec
      
      - name: Compile workbook and solutionbook
        run: |
          # Compile workbook (without solutions)
          echo "Building workbook..."
          cp main.tex main_workbook.tex
          sed -i 's/\\solutionstrue/\\solutionsfalse/' main_workbook.tex
          latexmk -pdf -interaction=nonstopmode main_workbook.tex
          mv main_workbook.pdf workbook.pdf
          
          # Compile solutionbook (with solutions) - use original main.tex
          echo "Building solutionbook..."
          latexmk -pdf -interaction=nonstopmode main.tex
          mv main.pdf solutionbook.pdf
      
      - name: Upload PDF files
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: |
            workbook.pdf
            solutionbook.pdf
      
      - name: Generate release tag
        id: tag
        run: |
            echo "release_tag=release_$(date +"%Y.%m.%d_%H-%M")" >> $GITHUB_OUTPUT
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
            files: |
              workbook.pdf
              solutionbook.pdf
            tag_name: ${{ steps.tag.outputs.release_tag }}
